name: pull-request-checks
on:
  pull_request:
    branches: [ develop ]

jobs:
  check-macos-10_15-cmake-clang:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Fetch dependencies
        run: brew install cmake ninja maven flex bison
      - name: Configure using CMake
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
      - name: Build with Ninja
        run: cd build; ninja
      - name: Run CTest
        run: cd build; ctest -V -L CORE .
  check-vs-2019-build-and-test:
    runs-on: windows-2019
    env:
      SCRIPT_DIR: .github/workflows/vs2019
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Update the submodules
        run: git submodule update --init

      - name: Install bison and flex
        run: ${{env.SCRIPT_DIR}}\install-bison.bat

      - name: Build cbmc
        run: ${{env.SCRIPT_DIR}}\build-cbmc.bat

      - name: Run tests
        run: ${{env.SCRIPT_DIR}}\run-tests.bat
